# DATABASE CONNECTION
# Uses environment variables if available (Cloud), otherwise defaults to localhost (Local)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/lms_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# DISABLE DEFAULT SECURITY (So API endpoints are accessible without login for now)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# MAIL SERVER CONFIGURATION (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:kimberlygobvu@gmail.com}
spring.mail.password=${MAIL_PASSWORD:kqvnzfnpzaphhitk}

# MAIL PROPERTIES
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true